### ISSUE TITLE
Better localization/multilanguage

### ISSUE THREAD

**Issue by DaniellMesquita** [HelloZeroNet/ZeroNet#1645]
- [ ] Languages folder on official sites (https://github.com/HelloZeroNet/ZeroNet/issues/1633)
- [ ] ZeroHello: recommend ZeroTalk according to language (https://github.com/HelloZeroNet/ZeroNet/issues/1632)
- [ ] ZeroHello and ZeroNet.io doesn't automatically detects pt-br (brazillian portuguese - https://github.com/HelloZeroNet/ZeroNet/issues/1616)
