### ISSUE TITLE
[Feature] User identy using quantum resistant addresses (QRL addresses)

### ISSUE THREAD

**Issue by DaniellMesquita** [HelloZeroNet/ZeroNet#1686]
# Description

> "There's a straightforward mitigation though: double the key size. In a post-quantum world, AES-256 is still comfortably secure. PGP and GPG are programs that use a variety of cryptographic algorithms. All of their asymmetric operations use algorithms (such as RSA and ECDSA) that are vulnerable to quantum computing".12 de fev de 2016
> * [Source](https://security.stackexchange.com/questions/103538/is-it-true-that-aes-128-and-aes-256-are-quantum-resistant)
> 
> "In early 2014 it was reported, based on documents provided by former NSA contractor Edward Snowden, that the U.S. National Security Agency (NSA) is running a $79.7 million research program (titled "Penetrating Hard Targets") to develop a quantum computer capable of breaking vulnerable encryption.[101]"
> 
> "In late 2017 and early 2018 IBM,[120] Intel,[121] and Google[122] each reported testing quantum processors containing 50, 49, and 72 qubits, respectively, all realized using superconducting circuits. By number of qubits, these circuits are approaching the range in which simulating their quantum dynamics is expected to become prohibitive on classical computers, although it has been argued that further improvements in error rates are needed to put classical simulation out of reach.[123]"
>  * [Source](https://en.wikipedia.org/wiki/Quantum_computing)

Quantum Resistant Ledger: https://theqrl.org/

# Tasks

- [ ] On ZeroHello, create the simplest (fastest) QRL identy address or more advanced depending on device's power (https://api.theqrl.org/?python#addnewaddress)
   - [ ] User receives its address' private key
   - [ ] User have option to get rid of this new address in order to create a stronger one
   - [ ] User can choose to login with its Bitcoin or QRL address
   - [ ] ZeroID/certificate system supports creation of certificates for identies that uses QRL address and logins
- [ ] Can sign files
- [ ] Can verify files (https://github.com/theQRL/QRL/blob/master/src/qrl/core/txs/Transaction.py#L276)

**Comment by DaniellMesquita** [comment]
https://github.com/theQRL/QRL

**Comment by DaniellMesquita** [comment]
@HelloZeroNet @shortcutme @tangdou1 @trenta3 @anoadragon453

**Comment by DaniellMesquita** [comment]
> Assuming we do consider quantum computing a threat, it probably wouldn't be too difficult to move over. "v2 sites" would have new addresses, some users would have new addresses too, and clients would just support both. A method for converting from less secure address types to the other would be ideal. One should just have to sign the site with their new quantum-resistent keys.

No need to "v2" sites for now. We can begin it for user identies.
v2 sites needs more than quantum resistant addresses.

**Comment by HelloZeroNet** [comment]
From the faq
> QRL implements one of a series of peer-reviewed post-quantum secure algorithms: XMSS (eXtended Merkle Signature Scheme) XMSS uses a OTS (One Time Signature Scheme) that can only sign one message with one key. 

It means this is not suitable for us, as it would mean the user files and the sites are only updateable once/limited time.

But I think we are far from when it became a problem. And if it do, then I'm pretty sure we will have time to fix/react to it.

**Comment by DaniellMesquita** [comment]
Reference: https://github.com/HelloZeroNet/ZeroNet/issues/185

**Comment by DaniellMesquita** [comment]
@shortcutme 
> It means this is not suitable for us, as it would mean the user files and the sites are only updateable once/limited time.

An QRL developer replied:
"but you could always point him to the XMSS whitepaper, and explain that a leaf node in the tree can sign another tree - which can be used to essentially generate infinite signatures from one root seed"

**Comment by DaniellMesquita** [comment]
https://blogs.scientificamerican.com/observations/quantum-computing-must-be-a-national-security-priority/
